### PR TITLE
feat: added mui, tailwind, initial config and removed unrequired components

### PR DESCRIPTION
**Pull request by adaptaconer**
PR that covers:

- Initial setup of MUI, Tailwind, React Icons
- Removal of components that will be covered by MUI components
- Temporary rewrite of GDS components that will be kept into Tailwind and MUI (we will need to review these and update styling again to match requirements, this was done to allow the build to pass for this PR)
- Updated build process to build with MUI and Tailwind
- Updated the Theme Provider to allow consumers to pass in an object of themes and choose an active one via another prop to allow theme switching from the user. (Probably should revisit this as well in the future to possible add in a `.gdsrc` file. I did play around with some options for this and `cosmiconfig` seems a good option but I couldn't get it working due to it being designed for packages not running in the browser so this needs more looking into.

Drop any questions or feedback below 😄

### CODE REVIEW

**Comment by adaptaconer** [comment]
Just pushed an update to update the remaining components so they use Tailwind and MUI and match the existing styles.

**Comment by adaptaconer** [comment]
Updated `Code` to include the line numbers and line highlighting mentioned in the migration document

**Comment by adaptajoe** [comment]
> Can we please de-capitalise `COPY` and `EXPAND` to just `Copy` and `Expand`?

**Comment by adaptajoe** [comment]
Please organise the `Utilities Introduction` page to remove references to now-defunct Utilities :)

**Comment by adaptajoe** [comment]
Screenshot 2023-05-25 at 11 41 54

`Code`'s `isOpenByDefault` Prop is broken 😄

**Comment by adaptaconer** [comment]
> Please organise the `Utilities Introduction` page to remove references to now-defunct Utilities :)

Sorted in the previous commit this morning. 😄

**Comment by adaptajoe** [comment]
Screenshot 2023-05-25 at 12 01 54

Bit of an odd one, but the Docs preview for `Code` is buggered for some reason?

**Comment by adaptaconer** [comment]
> `Code`'s `isOpenByDefault` Prop is broken 😄

Fixed in the latest commit.

> Bit of an odd one, but the Docs preview for `Code` is buggered for some reason?
> 
> EDIT: Actually _all_ of the Docs previews are oddly misstyled - May be a bug with Tailwind?

Also fixed in the latest commit, it looked like a bug in how Storybook was rendering the styles from Tailwind in the Preview page. I've updated to the latest Storybook version, seems to be working all good locally now.

**Comment by adaptaconer** [comment]
This PR is now ready for a final review @adaptajoe & @rahuladaptavist. It should have everything covered from the migration document that needs to be completed in the GDS.

I've switched the base branch to `main` as I don't believe we need the `feature/version-2` branch anymore as this PR should cover it all. 

Any questions just let me know.

**Review by adaptajoe — APPROVED** [review]

**Review by rahuladaptavist — APPROVED** [review]

**Pull request merged**
